### ISSUE TITLE
re-training needed for new pdb files? evaluating the AF2-multimer prediction?

### ISSUE THREAD

**Issue by avilella** [luost26/RDE-PPI#2]
Hi,

I have pdb files of 2 molecules (an antibody and an antigen) predicted by Alphafold2-multimer.

Do I need to re-train RDE-PPI to run `pointmut_analysis.py`?

If I am not sure about the quality of the AF2-multimer prediction, could the results of doing a mutational sweep with `pointmut_analysis.py` give me an indication of the validity of the AF2-multimer pdb? What should I be looking for in the resulting numbers? 

Thx in advance.

**Comment by luost26** [comment]
Hi,

Generally, there is no need to re-train the model for other PPI structures.

The model is expected to work well on experimentally determined structures. I am not sure whether it can give some indication of the quality of AF2-predicted structures. Perhaps the entropy might have some weak correlation with the quality of predicted structures? As entropy can be considered as some energy function, native-like structures should have lower entropy.

The `pointmut_analysis.py` script outputs a csv file `pm_results.csv`. The first column is the mutation name, the second column is ddG (lower implies higher binding affinity), and the last column is the percentile ranking.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/45375360/223086769-33379d02-e641-4eef-bcf6-373554103ad4.png">

Thanks.

**Comment by avilella** [comment]
Thanks.

What's the difference between the `mutations:` section in the yml file and
the `interests:` section?
Where should I do the sweep of antibody amino acid changes? Would doing a
sweep on antigen amino-acid changes give any relevant information?

Out of an ensembl of pdbs, would the one with the minimal ddG for the full
antibody amino-acid sweep be the most "believable" prediction?

Thanks in advance.

**Comment by luost26** [comment]
1. `interest` section is optional. It specifies which mutations of interest will be printed directly to the screen after finishing.

2. In principle, anywhere on the binding interface (both antibody and antigen) works.

3. I think it is reasonable but I am not sure about it.

**Comment by avilella** [comment]
Got it, thanks.
