### ISSUE TITLE
Question about the spatial attention implementation

### ISSUE THREAD

**Issue by chocolate9624** [luost26/RDE-PPI#3]
Hello, first of all many thanks for providing the source code alongside the paper.

` logits_spatial = self._spatial_logits(R, t, x)` [modules/encoders/attn.py](https://github.com/luost26/RDE-PPI/blob/main/rde/modules/encoders/attn.py#L160)
As the quote shows, I find the input variable `x` for `self._spatial_logits` is  the hidden representation from amino acid types and dihedral features,  rather atom coordinates.  

Since it is not spatial related input, how can we get spatial related logit?  What is the meaning of the sub functions in `_spatial_logits`, like `local_to_global` and `global_to_local`?

Could you help me understand this problem?  Or am I misunderstanding something?

Thank you very much.

**Comment by lipan6461188** [comment]
@chocolate9624 
In my view, although the **initialized** `x` does not contain any spatial information, the x can be updated by pair-wise spatial information from `z`. You can look [the follow code](https://github.com/luost26/RDE-PPI/blob/f6d68a7331a9f65290f525f0a491848245b072b3/rde/modules/encoders/attn.py#L195):
```python
        for block in self.blocks:
            res_feat = block(R, t, res_feat, pair_feat, mask)
```
The variable `res_feat` can be updated by `pair_feat`. So after several iterations, the `res_feat` (or `x`) should contain the spatial information.
